services:
  web:
    build:
      context: D:/AfraKalaTest/wt-torob-eye
      dockerfile: Dockerfile
    environment:
      TOROB_OPS_WORKER_TOKEN: ${TOROB_OPS_WORKER_TOKEN:-}
      TOROB_OPS_ACCOUNT_SECRET: ${TOROB_OPS_ACCOUNT_SECRET:-}
      TOROB_OPS_WORKER_ACTOR_ID: ${TOROB_OPS_WORKER_ACTOR_ID:-}
      TOROB_OPS_SIMULATE_SUBMIT: ${TOROB_OPS_SIMULATE_SUBMIT:-}
      TOROB_EYE_BOT_KEY: ${TOROB_EYE_BOT_KEY:-}
  torob-eye:
    build:
      context: D:/AfraKalaTest/wt-torob-eye/workers/torob-eye
      dockerfile: Dockerfile
    environment:
      TOROB_EYE_BOT_KEY: ${TOROB_EYE_BOT_KEY:-}
      TOROB_OPS_SIMULATE_SUBMIT: ${TOROB_OPS_SIMULATE_SUBMIT:-}
      TOROB_OPS_ACCOUNT_SECRET: ${TOROB_OPS_ACCOUNT_SECRET:-}
      TOROB_EYE_STUB_BLOCK: ${TOROB_EYE_STUB_BLOCK:-0}
