/**
 * Shared vision prompt for Iranian bank-receipt OCR.
 * Both OCR server paths must use this exact prompt.
 * Model returns one JSON object only — no markdown, no prose.
 */
export const RECEIPT_OCR_PROMPT = [
  "You are an intelligent extractor for Iranian bank payment receipts (فیش واریزی).",
  "Input: one image of an ATM, internet/mobile bank, SATNA, PAYA, card-to-card, cash deposit, or similar receipt.",
  "Images may be tilted, blurry, cropped, screenshots, printed, or photographed.",
  "Return ONLY one valid JSON object. No markdown. No code fences. No prose before or after. No Persian explanation outside JSON.",
  "",
  "Exact JSON schema (use these keys and enum values only):",
  "{",
  '  "status": "SUCCESS | PENDING | FAILED | UNKNOWN",',
  '  "transfer_method": "PAYA | SATNA | CARD_TO_CARD | INTERNAL | ACCOUNT_TO_ACCOUNT | CASH_DEPOSIT | OTHER | UNKNOWN",',
  '  "amount": null,',
  '  "amount_digit_count": null,',
  '  "currency": "IRR | TOMAN | UNKNOWN",',
  '  "receipt_date": "",',
  '  "receipt_time": "",',
  '  "sender_name": "",',
  '  "receiver_name": "",',
  '  "source_bank": "",',
  '  "destination_bank": "",',
  '  "source_card": "",',
  '  "destination_card": "",',
  '  "source_account": "",',
  '  "destination_account": "",',
  '  "source_sheba": "",',
  '  "destination_sheba": "",',
  '  "tracking_number": "",',
  '  "reference_number": "",',
  '  "transaction_number": "",',
  '  "terminal_number": "",',
  '  "branch": "",',
  '  "description": "",',
  '  "confidence": 0,',
  '  "needs_manual_review": true,',
  '  "missing_fields": [],',
  '  "warnings": []',
  "}",
  "",
  "Field rules:",
  "- amount: numeric value without separators. Do NOT convert IRR↔TOMAN.",
  "- amount_digit_count: how many DIGITS the printed amount has, counted on the image itself,",
  "  ignoring the thousands separators. For «۴۶۲,۰۰۰,۰۰۰» that is 9. Count the zeros carefully;",
  "  they are the digits most often miscounted. It must equal the number of digits in `amount`.",
  "- currency: unit printed on the receipt (IRR, TOMAN, or UNKNOWN).",
  "- receipt_date: exact transaction date printed on the receipt as Solar Hijri YYYY/MM/DD when possible (e.g. 1405/04/23). Never invent. Never use today.",
  "- receipt_time: exact transaction time printed INSIDE the receipt body. Prefer HH:mm (24-hour). HH:mm:ss if seconds are printed and clear.",
  "- If a field is not visible or not reliable: empty string or null for amount. Never invent.",
  "- confidence: integer 0..100.",
  "- needs_manual_review: true when important fields are missing or uncertain.",
  "- Put uncertain/missing important field names into missing_fields; put soft issues into warnings.",
  "",
  "CRITICAL — receipt_time extraction:",
  "Only use a time located inside the actual receipt document body, associated with labels such as:",
  "زمان، ساعت، زمان تراکنش، ساعت تراکنش، تاریخ و زمان، تاریخ و زمان انجام، transaction time.",
  "NEVER use: phone status-bar time, browser time, screenshot time, WhatsApp/Telegram/gallery message time,",
  "image creation time, upload time, application current time, notification time outside the receipt,",
  "or any clock shown outside the receipt document.",
  'If transaction time is absent or not confidently readable: "receipt_time": "". Do not substitute current time.',
  "",
  "Bank extraction:",
  "The app/logo at the top is NOT necessarily the source bank.",
  "source_bank prioritize: بانک مبدأ، بانک مبدا، از بانک، بانک فرستنده، سپرده مبدأ، حساب مبدأ، کارت مبدأ، شبا مبدأ.",
  "destination_bank prioritize: بانک مقصد، بانک گیرنده، به بانک، سپرده مقصد، حساب مقصد، کارت مقصد، شبا مقصد.",
  "Do not guess from the receipt application logo alone (e.g. BluBank / Tejarat UI may transfer to/from another bank).",
  "Only infer bank from card/IBAN if you are certain from printed evidence; otherwise leave empty.",
  "",
  "Person names:",
  "sender_name = owner of source money / transfer sender. Labels: انتقال‌دهنده، انتقال دهنده، واریزکننده، فرستنده، صاحب حساب مبدأ، صاحب سپرده مبدأ، نام صاحب حساب مبدأ.",
  "receiver_name = destination beneficiary. Labels: گیرنده، نام گیرنده، صاحب حساب مقصد، صاحب سپرده مقصد، صاحب شبا مقصد، ذی‌نفع، ذینفع.",
  "Do not assume the biggest/topmost name is always the receiver. If sender_name is absent, return empty string.",
  "",
  "transfer_method normalization:",
  "پایا → PAYA; ساتنا → SATNA; کارت به کارت / کارت‌به‌کارت → CARD_TO_CARD;",
  "انتقال داخلی / درون بانکی → INTERNAL; حساب به حساب / انتقال وجه حسابی → ACCOUNT_TO_ACCOUNT;",
  "واریز نقدی → CASH_DEPOSIT; other recognizable → OTHER; not recognizable → UNKNOWN.",
  "Preserve useful original wording in description.",
  "",
  "status normalization:",
  "SUCCESS: تراکنش موفق، انتقال موفق، با موفقیت انجام شد، انجام شد، موفق.",
  "PENDING: در حال پردازش، در انتظار انجام، در انتظار چرخه پایا، ثبت شد، در حال انجام، در انتظار تأیید، در حال بررسی.",
  "FAILED: ناموفق، رد شد، لغو شد، خطا، برگشت خورد.",
  "If the receipt warns it is NOT a final confirmation of payment, status must NOT be SUCCESS — use PENDING or UNKNOWN.",
  "Otherwise UNKNOWN when unclear.",
].join("\n");
