import {
  LayoutDashboard,
  Package,
  DollarSign,
  ShoppingCart,
  ShoppingBag,
  FileText,
  ListOrdered,
  Users,
  ShieldCheck,
  BarChart3,
  BookOpen,
  MessageSquare,
  ScrollText,
  Database,
  KeyRound,
  UserSquare2,
  Factory,
  GraduationCap,
  CheckSquare,
  Workflow,
  Settings,
  Heart,
  Megaphone,
  Edit3,
  Monitor,
  TrendingUp,
  Trophy,
  Wallet,
  Coins,
  Plus,
  Tag,
  Layers,
  Bookmark,
  Bell,
  Calculator,
  Sparkles,
  Banknote,
  AlertTriangle,
  Send,
  Share2,
  Receipt,
  CreditCard,
  BadgeCheck,
  LifeBuoy,
  FileCheck,
  ClipboardList,
  Plug,
} from "lucide-react";
import type { ModuleKey } from "@/lib/rbac/roles";

export interface NavItem {
  to: string;
  label: string;
  icon: typeof LayoutDashboard;
  module: ModuleKey;
  group:
    | "main"
    | "products-pricing"
    | "purchasing"
    | "sales-customers"
    | "finance"
    | "operations"
    | "reports"
    | "knowledge-comms"
    | "admin";
  /** Optional 2nd-level group label inside a top-level group. */
  subgroup?: SubgroupKey;
  /** When true, only admin/manager roles see this item even if module check passes. */
  adminOnly?: boolean;
}

export type SubgroupKey =
  // products-pricing
  | "pp-catalog"
  | "pp-pricing"
  | "pp-publish"
  // sales-customers
  | "sc-sales"
  | "sc-customers"
  // admin
  | "adm-users"
  | "adm-settings"
  | "adm-gamification"
  | "adm-tools";

export const NAV_ITEMS: NavItem[] = [
  // ۱) داشبورد
  { to: "/dashboard", label: "داشبورد", icon: LayoutDashboard, module: "dashboard", group: "main" },
  { to: "/notifications", label: "اعلان‌ها", icon: Bell, module: "messages", group: "main" },
  { to: "/popup-center", label: "مرکز پاپ‌آپ‌ها", icon: Bell, module: "dashboard", group: "main" },
  {
    to: "/collaboration",
    label: "ارتباطات همکاری",
    icon: MessageSquare,
    module: "messages",
    group: "main",
  },

  // ۲) محصولات و قیمت‌گذاری
  {
    to: "/products",
    label: "محصولات",
    icon: Package,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/new",
    label: "افزودن محصول",
    icon: Plus,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/categories",
    label: "دسته‌بندی‌ها",
    icon: Layers,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/brands",
    label: "برندها",
    icon: Bookmark,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/attributes",
    label: "ویژگی‌ها",
    icon: Tag,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/labels",
    label: "برچسب‌ها",
    icon: Tag,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/pricing/purchase-prices",
    label: "قیمت‌های خرید",
    icon: ShoppingBag,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/rules",
    label: "قوانین قیمت‌گذاری",
    icon: Workflow,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/sale-price-types",
    label: "نوع‌های قیمت فروش",
    icon: DollarSign,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/quick-price",
    label: "قیمت سریع",
    icon: Sparkles,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/calculator",
    label: "ماشین‌حساب قیمت",
    icon: Calculator,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/my-workbench",
    label: "کارگاه قیمت من",
    icon: Edit3,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/attention",
    label: "فرصت جبران",
    icon: LifeBuoy,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/price-alerts",
    label: "هشدارهای قیمت",
    icon: AlertTriangle,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/market-intelligence",
    label: "هوشمند بازار",
    icon: TrendingUp,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/product-recommendations",
    label: "پیشنهاد محصولات",
    icon: Sparkles,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-pricing",
    adminOnly: true,
  },
  {
    to: "/pricing/amin-hozoor-board",
    label: "تابلو قیمت زنده",
    icon: Monitor,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/live-price-list",
    label: "لیست قیمت زنده",
    icon: ListOrdered,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/sale-lists",
    label: "لیست قیمت فروش",
    icon: FileText,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/recompute-prices",
    label: "انتشار دسته‌ای قیمت",
    icon: Sparkles,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
    adminOnly: true,
  },

  // ۳) خرید و تأمین‌کنندگان
  {
    to: "/suppliers",
    label: "تأمین‌کنندگان",
    icon: Factory,
    module: "suppliers",
    group: "purchasing",
  },
  {
    to: "/purchases",
    label: "پنل خرید",
    icon: ShoppingBag,
    module: "purchases",
    group: "purchasing",
  },

  // ۴) فروش و مشتریان
  {
    to: "/sales",
    label: "جستجوی سریع فروش",
    icon: ShoppingCart,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/quotes",
    label: "پیش‌فاکتورها",
    icon: FileText,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/invoices",
    label: "فاکتورهای فروش",
    icon: Receipt,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/invoices",
    label: "فاکتورها",
    icon: FileText,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/stock-alerts",
    label: "هشدار موجودی",
    icon: AlertTriangle,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/customers",
    label: "مشتریان",
    icon: UserSquare2,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/persons",
    label: "اشخاص",
    icon: UserSquare2,
    module: "persons",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/sales/credit-customers",
    label: "اعتبار مشتریان",
    icon: BadgeCheck,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/sales/credit-rules",
    label: "قوانین اعتبار",
    icon: ShieldCheck,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },

  // ۵) مالی و حسابداری
  // UI-NAV.4 — همگی به ماژول جدید «accounting» منتقل شدند تا برای فروشنده/بیننده پنهان شوند.
  {
    to: "/accounting/receipts",
    label: "فیش‌های واریزی",
    icon: Receipt,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/receivables",
    label: "مطالبات مشتریان",
    icon: Wallet,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/payables",
    label: "بدهی تأمین‌کنندگان",
    icon: Wallet,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/purchase-payments",
    label: "پرداخت خرید",
    icon: CreditCard,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/bank-accounts",
    label: "حساب‌های بانکی",
    icon: Banknote,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/external-parties",
    label: "طرف‌های حساب",
    icon: UserSquare2,
    module: "accounting",
    group: "finance",
  },
  // Item 141 — the three legacy capital pages
  // (/accounting/customer-capital-allocations, /accounting/salesperson-capital-allocations,
  // /accounting/daily-capital) were removed from navigation. Their routes now
  // redirect to /accounting/dynamic-capital, which is the single official page.
  {
    to: "/accounting/dynamic-capital",
    label: "تخصیص سرمایه پویا",
    icon: Coins,
    module: "accounting",
    group: "finance",
  },

  // ۶) عملیات داخلی
  {
    to: "/operations/tasks",
    label: "برد وظایف",
    icon: CheckSquare,
    module: "invoices",
    group: "operations",
  },
  {
    to: "/operations/daily-mood",
    label: "حال‌وهوای امروز",
    icon: Heart,
    module: "feedback",
    group: "operations",
  },
  {
    to: "/operations/daily-mood/admin",
    label: "مدیریت حال‌وهوا",
    icon: Heart,
    module: "hr",
    group: "operations",
    adminOnly: true,
  },
  {
    to: "/feedback",
    label: "بازخورد",
    icon: MessageSquare,
    module: "feedback",
    group: "operations",
  },
  {
    to: "/gamification",
    label: "داشبورد گیمیفیکیشن",
    icon: Trophy,
    module: "dashboard",
    group: "operations",
  },
  {
    to: "/gamification/leaderboard",
    label: "لیدربورد",
    icon: BarChart3,
    module: "dashboard",
    group: "operations",
  },

  // ۷) گزارش‌ها
  { to: "/reports", label: "گزارش‌ها", icon: BarChart3, module: "reports", group: "reports" },
  {
    to: "/audit-logs",
    label: "لاگ فعالیت‌ها",
    icon: ScrollText,
    module: "audit-logs",
    group: "reports",
    adminOnly: true,
  },
  {
    to: "/sales/quote-share-logs",
    label: "لاگ اشتراک‌گذاری پیش‌فاکتور",
    icon: Share2,
    module: "invoices",
    group: "reports",
  },
  { to: "/sales/send-queue", label: "صف ارسال", icon: Send, module: "invoices", group: "reports" },
  {
    to: "/marketing/suggestions",
    label: "پیشنهادهای تبلیغاتی",
    icon: Megaphone,
    module: "reports",
    group: "reports",
  },
  {
    to: "/marketing/suggestions-history",
    label: "تاریخچه پیشنهادها",
    icon: ScrollText,
    module: "reports",
    group: "reports",
  },

  // ۸) دانش، آکادمی و ارتباطات
  {
    to: "/knowledge",
    label: "دانش سازمانی",
    icon: BookOpen,
    module: "knowledge",
    group: "knowledge-comms",
  },
  {
    to: "/academy",
    label: "آکادمی",
    icon: GraduationCap,
    module: "academy",
    group: "knowledge-comms",
  },
  {
    to: "/data-tables",
    label: "جداول داده پویا",
    icon: Database,
    module: "data-tables",
    group: "knowledge-comms",
  },

  // ۹) مدیریت سیستم
  {
    to: "/users",
    label: "کاربران",
    icon: Users,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
  },
  {
    to: "/users/pending",
    label: "کاربران در انتظار تأیید",
    icon: Users,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/roles",
    label: "نقش‌ها و دسترسی‌ها",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-users",
  },
  {
    to: "/admin/roles",
    label: "مجوزهای پویا",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/admin/profile-fields",
    label: "فیلدهای کاربر",
    icon: UserSquare2,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/admin/settings",
    label: "تنظیمات عمومی",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/penalties",
    label: "کارت‌های قرمز",
    icon: AlertTriangle,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/audit",
    label: "لاگ فعالیت‌ها",
    icon: ClipboardList,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/purchase",
    label: "مدیریت خرید",
    icon: ShoppingCart,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/documents",
    label: "مدیریت اسناد",
    icon: FileText,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/delivery-receipts",
    label: "مدیریت رسیدها",
    icon: FileCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/workflow-settings",
    label: "تنظیمات گردش‌کار",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/marketing-channels",
    label: "کانال‌های تبلیغاتی",
    icon: Megaphone,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/sales-reminders",
    label: "یادآوری‌های فروش",
    icon: MessageSquare,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/payment-terms",
    label: "زمان‌های تسویه",
    icon: Wallet,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/waybill-fields",
    label: "فیلدهای بیجک",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/receipt-fields",
    label: "فیلدهای فیش واریزی",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/recent-purchase-settings",
    label: "وضعیت موجودی پس از خرید",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/workflow-stages",
    label: "مراحل گردش‌کار",
    icon: Workflow,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/validation-rules",
    label: "قوانین اعتبارسنجی",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currencies",
    label: "ارزها",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currency-sources",
    label: "منابع ارز",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currency-rates",
    label: "نرخ ارز",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/market-rates-workshop",
    label: "کارگاه نرخ ارز و طلا",
    icon: Coins,
    module: "market-rates",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/settlement-types",
    label: "انواع تسویه",
    icon: Wallet,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/shipping-rules",
    label: "قوانین ارسال",
    icon: Workflow,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/change-reasons",
    label: "دلایل تغییر قیمت",
    icon: ScrollText,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing",
    label: "تنظیمات قیمت‌گذاری",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/automation",
    label: "اتوماسیون فاز صفر",
    icon: Sparkles,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/bot-api-keys",
    label: "کلیدهای API ربات",
    icon: KeyRound,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
  },
  {
    to: "/integrations/didar",
    label: "یکپارچه‌سازی دیدار",
    icon: Plug,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/market-matches",
    label: "بررسی تطبیق محصولات بازار",
    icon: BadgeCheck,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/kpi-rules",
    label: "قوانین امتیازدهی",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/achievements",
    label: "مدیریت مدال‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/missions",
    label: "مدیریت مأموریت‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/leagues",
    label: "مدیریت لیگ‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/rewards",
    label: "مدیریت پاداش‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/analytics",
    label: "تحلیل گیمیفیکیشن",
    icon: BarChart3,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/purchase-settings",
    label: "طلای زمان (خرید)",
    icon: Coins,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  // Item 132.1 — manual daily performance entry (admin/manager/accountant).
  {
    to: "/gamification/admin/manual-metrics",
    label: "ثبت دستی عملکرد روزانه",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
];

export const GROUP_LABELS: Record<NavItem["group"], string> = {
  main: "داشبورد",
  "products-pricing": "محصولات و قیمت‌گذاری",
  purchasing: "خرید و تأمین‌کنندگان",
  "sales-customers": "فروش و مشتریان",
  finance: "مالی و حسابداری",
  operations: "عملیات داخلی",
  reports: "گزارش‌ها",
  "knowledge-comms": "دانش، آکادمی و ارتباطات",
  admin: "مدیریت سیستم",
};

export const SUBGROUP_LABELS: Record<SubgroupKey, string> = {
  "pp-catalog": "اطلاعات کالا",
  "pp-pricing": "قیمت‌گذاری",
  "pp-publish": "انتشار و لیست‌ها",
  "sc-sales": "فروش",
  "sc-customers": "مشتریان و اعتبار",
  "adm-users": "کاربران و دسترسی‌ها",
  "adm-settings": "تنظیمات",
  "adm-gamification": "مدیریت گیمیفیکیشن",
  "adm-tools": "ابزارها و یکپارچه‌سازی",
};
