# release/emit-blocks.ps1
# Generates release/out/RELEASE-<date>.md in BLOCKS.md's own format: one block per unit of work,
# each with a literal "Expect:" line, so release/validate-blocks.ps1 can check it mechanically and
# release/apply-release.ps1 can execute it mechanically. ASCII-only, PowerShell 5.1 compatible.
#
# WHY GENERATED, NOT HAND-WRITTEN
#   docs/research/convergence/R-4-transfer-line.md Task 1.2 found that the 09-12 run's claim of
#   "validated mechanically" was never backed by a real script, and that the underlying BLOCKS.md
#   document is hand-authored prose every time. Generating it from a PASSED rehearsal report closes
#   both gaps at once: the document cannot exist without a rehearsal behind it, and its migration
#   list cannot drift from what was actually classified and replayed.
#
# THIS SCRIPT REFUSES TO RUN if the rehearsal it is given did not PASS, or is missing entirely --
# a release document generated without a rehearsal behind it is exactly the risk this pipeline
# exists to remove.
#
# USAGE
#   .\release\emit-blocks.ps1 -RehearsalReport release\out\rehearsal-20260912.md -Date 20260912
#       [-BuildManifest release\out\build-<sha>.json] [-Tarball release\out\afrakala-app-<sha>.tar.gz]

param(
    [Parameter(Mandatory = $true)][string]$RehearsalReport,
    [Parameter(Mandatory = $true)][string]$Date,
    [string]$BuildManifest = "",
    [string]$Tarball = ""
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $RehearsalReport)) {
    Write-Host "FATAL: rehearsal report not found: $RehearsalReport" -ForegroundColor Red
    Write-Host "A RELEASE document is never generated without a rehearsal behind it." -ForegroundColor Yellow
    exit 1
}

$report = Get-Content -Path $RehearsalReport -Encoding UTF8 -Raw
$reportLines = Get-Content -Path $RehearsalReport -Encoding UTF8

if ($report -notmatch "## VERDICT: PASS") {
    Write-Host "FATAL: rehearsal report does not say 'VERDICT: PASS'." -ForegroundColor Red
    Write-Host "Found instead:" -ForegroundColor Yellow
    $reportLines | Where-Object { $_ -match "VERDICT" } | ForEach-Object { Write-Host "  $_" }
    exit 1
}

function Get-ValueAfter {
    param([string[]]$Lines, [string]$Marker)
    $m = $Lines | Where-Object { $_ -match [regex]::Escape($Marker) } | Select-Object -First 1
    if (-not $m) { return $null }
    return ($m -split '=', 2)[1].Trim()
}

$dumpFile = ($reportLines | Where-Object { $_ -match '^dump file\s*:' } | Select-Object -First 1) -replace '^dump file\s*:\s*', ''
$dumpMd5 = ($reportLines | Where-Object { $_ -match '^md5 \(host\)\s*:' } | Select-Object -First 1) -replace '^md5 \(host\)\s*:\s*', ''
$ledgerBefore = Get-ValueAfter -Lines $reportLines -Marker "ledger_rows|ledger_min|ledger_max"
$preflight = Get-ValueAfter -Lines $reportLines -Marker "is_replica|db_size|anon_default_acl_count"

# --- parse the machine-readable classification block --------------------------------------------
$startIdx = ($reportLines | Select-String -Pattern '## Machine-readable classification' | Select-Object -First 1).LineNumber
if (-not $startIdx) {
    Write-Host "FATAL: rehearsal report has no machine-readable classification section." -ForegroundColor Red
    exit 1
}
$fenceLines = $reportLines[($startIdx)..($reportLines.Count - 1)]
$inFence = $false
$classified = New-Object System.Collections.Generic.List[object]
foreach ($l in $fenceLines) {
    if ($l.Trim() -eq '```') {
        if ($inFence) { break } else { $inFence = $true; continue }
    }
    if ($inFence -and $l.Trim() -ne '') {
        $parts = $l -split '\|'
        if ($parts.Count -ge 2) {
            $fileVal = ""
            if ($parts.Count -ge 3) { $fileVal = $parts[2] }
            $classified.Add([PSCustomObject]@{ Version = $parts[0]; Bucket = $parts[1]; File = $fileVal })
        }
    }
}

$applyList = $classified | Where-Object { $_.Bucket -eq 'APPLY' } | Sort-Object Version
$ledgerOnlyList = $classified | Where-Object { $_.Bucket -eq 'LEDGER_ONLY' } | Sort-Object Version

Write-Host "Parsed rehearsal: $($applyList.Count) APPLY, $($ledgerOnlyList.Count) LEDGER_ONLY" -ForegroundColor Cyan

$outDir = Join-Path $PSScriptRoot "out"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
$outFile = Join-Path $outDir "RELEASE-$Date.md"

$sb = New-Object System.Text.StringBuilder
function Add-Line([string]$s) { [void]$sb.AppendLine($s) }

Add-Line "# RELEASE-$Date"
Add-Line ""
Add-Line "Generated by release/emit-blocks.ps1 from a PASSED rehearsal: $RehearsalReport"
Add-Line "Rehearsal restore source: $dumpFile (md5 $dumpMd5)"
Add-Line ""
[void]$sb.AppendLine(@'
Every block below has a literal 'Expect:' line. release/validate-blocks.ps1 checks this
document mechanically before anyone runs it. release/apply-release.ps1 stops at the FIRST
block whose live output disagrees with its Expect: line -- exactly BLOCKS.md's own rule.

---

### Block 1 - Preflight
'@)
Add-Line ""
[void]$sb.AppendLine(@'
    docker exec afrakala-lan-db psql -U supabase_admin -d postgres -tAc \
      "SELECT pg_is_in_recovery() || '|' || pg_size_pretty(pg_database_size(current_database())) || '|' ||
       (SELECT count(*) FROM pg_default_acl WHERE defaclacl::text LIKE '%anon%');"
'@)
Add-Line ""
Add-Line "Expect: is_replica|db_size|anon_default_acl_count = $preflight"
Add-Line "Expect: pg_is_in_recovery() = f (a replica must STOP this run immediately)"
Add-Line ""
[void]$sb.AppendLine(@'
    docker exec afrakala-lan-db psql -U supabase_admin -d postgres -tAc \
      "SELECT count(*) || '|' || min(version) || '|' || max(version) FROM supabase_migrations.schema_migrations;"
'@)
Add-Line ""
Add-Line "Expect: ledger_rows|ledger_min|ledger_max = $ledgerBefore"
[void]$sb.AppendLine(@'
(this is the state the rehearsal observed on the restored dump; if production disagrees, STOP
and re-run release/rehearse.ps1 against a fresher dump before proceeding)

---

# Phase 4 - migrations
'@)
Add-Line ""

$blockN = 2
foreach ($m in $applyList) {
    Add-Line "### Block $blockN - migration $($m.Version) . $($m.File)"
    Add-Line ""
    Add-Line "    mig_apply $($m.Version) $($m.File)"
    Add-Line ""
    Add-Line "Expect: OK $($m.File)"
    Add-Line "Expect: INSERT 0 1"
    Add-Line ""
    $blockN++
}

foreach ($m in $ledgerOnlyList) {
    Add-Line "### Block $blockN - ledger-row-only $($m.Version) . $($m.File)"
    Add-Line ""
    [void]$sb.AppendLine(@'
Catalogue evidence in the rehearsal showed this migration's effect is already PRESENT but
the ledger has no row for it (applied-but-unrecorded, CLAUDE.md rule 2b). The SQL is NOT
re-run. Only the ledger row is written.
'@)
    Add-Line ""
    Add-Line "    ledger_insert_only $($m.Version)"
    Add-Line ""
    Add-Line "Expect: INSERT 0 1"
    Add-Line "Expect: OK ledger-row-only $($m.Version)"
    Add-Line ""
    $blockN++
}

Add-Line "---"
Add-Line ""
Add-Line "# Phase 5 - image"
Add-Line ""
Add-Line "### Block $blockN - image transfer"
Add-Line ""
if ($BuildManifest -ne "" -and (Test-Path $BuildManifest)) {
    $manifest = Get-Content $BuildManifest -Raw | ConvertFrom-Json
    Add-Line "Built by release/build.ps1 from main @ $($manifest.git_sha)."
    Add-Line ""
    Add-Line "    # deliver the tarball over the proven LAN channel (SMB share \\192.168.170.8\dumps),"
    Add-Line "    # then on the target machine:"
    Add-Line "    gunzip -c afrakala-app-$($manifest.git_sha).tar.gz | docker load"
    Add-Line "    docker tag afrakala-app:$($manifest.git_sha) afrakala-app:lan"
    [void]$sb.AppendLine('    docker images afrakala-app:lan --format "{{.ID}}"')
    Add-Line ""
    Add-Line "Expect: loaded image ID = $($manifest.image_id)"
} else {
    [void]$sb.AppendLine(@'
No build manifest was supplied to emit-blocks.ps1 (-BuildManifest). Run release/build.ps1
first, then re-generate this document, or fill this block in by hand before applying:

    gunzip -c afrakala-app-<sha>.tar.gz | docker load
    docker tag afrakala-app:<sha> afrakala-app:lan
    docker images afrakala-app:lan --format "{{.ID}}"

Expect: loaded image ID = <fill in from release/out/build-<sha>.json>
'@)
}
Add-Line ""
$blockN++

Add-Line "---"
Add-Line ""
Add-Line "# Phase 6 - deploy"
Add-Line ""
Add-Line "### Block $blockN - rollback tag"
Add-Line ""
[void]$sb.AppendLine(@'
ONE convention, always: 'afrakala-app:lan-rollback'. Five differently-named stale tags existed
before this pipeline (lan-rollback-before-pv-remediation, lan-rollback-before-revert,
lan-rollback-settlement-price, lan-rollback-before-quote-autofill, and an unnamed one) and were
deleted by the orchestrator because none of them was the agreed name. This block also prunes
any OTHER tag matching 'afrakala-app:lan-rollback-*' so exactly one rollback tag ever exists.

    docker tag afrakala-app:lan afrakala-app:lan-rollback
    docker images afrakala-app --format "{{.Repository}}:{{.Tag}}" | Select-String 'lan-rollback-' | ForEach-Object { docker rmi $_.Line }
    docker images afrakala-app --format "{{.Repository}}:{{.Tag}}`t{{.CreatedAt}}"

Expect: afrakala-app:lan-rollback present; no afrakala-app:lan-rollback-* tag remains
'@)
Add-Line ""
$blockN++

Add-Line "### Block $blockN - deploy"
Add-Line ""
[void]$sb.AppendLine(@'
    $env:GIT_SHA = (git rev-parse --short HEAD)
    $env:BUILD_TIME = (Get-Date -Format o)
    docker compose --env-file deploy/lan/.env.lan -f deploy/lan/docker-compose.yml `
      up -d --no-deps --no-build web
    docker restart afrakala-lan-rest

Expect: --no-deps present (its absence takes the whole app down, CLAUDE.md OG-68)
Expect: GIT_SHA set on the command line (its absence silently mislabels the running image)
Expect: afrakala-lan-rest   Up X seconds
'@)
Add-Line ""
$blockN++

Add-Line "### Block $blockN - verify"
Add-Line ""
[void]$sb.AppendLine(@'
    docker inspect afrakala-lan-web --format "{{range .Config.Env}}{{println .}}{{end}}" | Select-String APP_GIT_SHA
    git rev-parse --short HEAD
    docker ps --filter name=afrakala-lan --format "{{.Names}}`t{{.Status}}"
    curl.exe -s -o NUL -w "%{http_code} %{time_total}`n" http://192.168.170.10:3000/login
    curl.exe -s -w "`n%{http_code}`n" http://192.168.170.10:3000/api/healthz

Expect: APP_GIT_SHA equals git rev-parse --short HEAD
Expect: afrakala-lan-db-role-fix = Exited (0); every other afrakala-lan-* = Up
Expect: /login = 200 under 1 second
Expect: /api/healthz = 200
'@)
Add-Line ""
$blockN++

Add-Line "---"
Add-Line ""
Add-Line "# Rollback"
Add-Line ""
Add-Line "### Block $blockN - rollback (run this instead of Block $($blockN - 2) if Block $($blockN - 1) fails)"
Add-Line ""
[void]$sb.AppendLine(@'
    docker tag afrakala-app:lan-rollback afrakala-app:lan
    docker compose --env-file deploy/lan/.env.lan -f deploy/lan/docker-compose.yml up -d --no-deps web

Expect: afrakala-lan-web returns to the image tagged afrakala-app:lan-rollback
(schema rollback, if a migration also needs undoing, is a separate manual step -- see
docs/deployment/rollback-plan.md; this pipeline's migrations are additive by CLAUDE.md rule 3
and do not ship an automatic down path)
'@)
Add-Line ""
$blockN++

Add-Line "---"
Add-Line ""
Add-Line "# Sign-off"
Add-Line ""
Add-Line "### Block $blockN - sign-off"
Add-Line ""
[void]$sb.AppendLine(@'
- [ ] og81  (ledger matches disk)              Expect: PASSED
- [ ] og102 (anon execute grants stay closed)   Expect: PASSED
- [ ] og103 (anon table grants stay closed)     Expect: PASSED
- [ ] smoke: receivables page loads
- [ ] smoke: payables page loads
- [ ] smoke: allocation workbench opens
- [ ] cold gate: viewer cannot reach /admin/automation

Executor: ______________     Date/time: ______________
'@)
Add-Line ""
Add-Line "Overall: PASSED / STOP  (circle one; STOP means Block $($blockN - 1)'s rollback was used)"

$sb.ToString() | Set-Content -Path $outFile -Encoding UTF8
Write-Host "Written: $outFile" -ForegroundColor Green
exit 0
