/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppPriceListsRouteImport } from './routes/_app.price-lists'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppProductsBrandsRouteImport } from './routes/_app.products.brands'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppProductsIdEditRouteImport } from './routes/_app.products.$id.edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsRoute = AppPriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsBrandsRoute = AppProductsBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsIdEditRoute = AppProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProductsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/invoices': typeof AppInvoicesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/messages': typeof AppMessagesRoute
  '/price-lists': typeof AppPriceListsRoute
  '/pricing': typeof AppPricingRoute
  '/products': typeof AppProductsRouteWithChildren
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/users': typeof AppUsersRoute
  '/products/$id': typeof AppProductsIdRouteWithChildren
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/invoices': typeof AppInvoicesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/messages': typeof AppMessagesRoute
  '/price-lists': typeof AppPriceListsRoute
  '/pricing': typeof AppPricingRoute
  '/products': typeof AppProductsRouteWithChildren
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/users': typeof AppUsersRoute
  '/products/$id': typeof AppProductsIdRouteWithChildren
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/price-lists': typeof AppPriceListsRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/products/$id': typeof AppProductsIdRouteWithChildren
  '/_app/products/brands': typeof AppProductsBrandsRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/audit-logs'
    | '/dashboard'
    | '/feedback'
    | '/invoices'
    | '/knowledge'
    | '/messages'
    | '/price-lists'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/users'
    | '/products/$id'
    | '/products/brands'
    | '/products/new'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/audit-logs'
    | '/dashboard'
    | '/feedback'
    | '/invoices'
    | '/knowledge'
    | '/messages'
    | '/price-lists'
    | '/pricing'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/users'
    | '/products/$id'
    | '/products/brands'
    | '/products/new'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/unauthorized'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/invoices'
    | '/_app/knowledge'
    | '/_app/messages'
    | '/_app/price-lists'
    | '/_app/pricing'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/sales'
    | '/_app/users'
    | '/_app/products/$id'
    | '/_app/products/brands'
    | '/_app/products/new'
    | '/_app/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists': {
      id: '/_app/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof AppPriceListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/brands': {
      id: '/_app/products/brands'
      path: '/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof AppProductsBrandsRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$id/edit': {
      id: '/_app/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AppProductsIdEditRouteImport
      parentRoute: typeof AppProductsIdRoute
    }
  }
}

interface AppProductsIdRouteChildren {
  AppProductsIdEditRoute: typeof AppProductsIdEditRoute
}

const AppProductsIdRouteChildren: AppProductsIdRouteChildren = {
  AppProductsIdEditRoute: AppProductsIdEditRoute,
}

const AppProductsIdRouteWithChildren = AppProductsIdRoute._addFileChildren(
  AppProductsIdRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRouteWithChildren
  AppProductsBrandsRoute: typeof AppProductsBrandsRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRouteWithChildren,
  AppProductsBrandsRoute: AppProductsBrandsRoute,
  AppProductsNewRoute: AppProductsNewRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPriceListsRoute: typeof AppPriceListsRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPriceListsRoute: AppPriceListsRoute,
  AppPricingRoute: AppPricingRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesRoute: AppSalesRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
