/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppPriceListsRouteImport } from './routes/_app.price-lists'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBotApiKeysRouteImport } from './routes/_app.bot-api-keys'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppPricingIndexRouteImport } from './routes/_app.pricing.index'
import { Route as AppDataTablesIndexRouteImport } from './routes/_app.data-tables.index'
import { Route as AppSalesStockAlertsRouteImport } from './routes/_app.sales.stock-alerts'
import { Route as AppSalesSendQueueRouteImport } from './routes/_app.sales.send-queue'
import { Route as AppSalesSearchRouteImport } from './routes/_app.sales.search'
import { Route as AppSalesQuotesRouteImport } from './routes/_app.sales.quotes'
import { Route as AppSalesQuoteShareLogsRouteImport } from './routes/_app.sales.quote-share-logs'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppProductsLabelsRouteImport } from './routes/_app.products.labels'
import { Route as AppProductsCategoriesRouteImport } from './routes/_app.products.categories'
import { Route as AppProductsBrandsRouteImport } from './routes/_app.products.brands'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppPricingShippingRulesRouteImport } from './routes/_app.pricing.shipping-rules'
import { Route as AppPricingSalePriceTypesRouteImport } from './routes/_app.pricing.sale-price-types'
import { Route as AppPricingRulesRouteImport } from './routes/_app.pricing.rules'
import { Route as AppPricingQuickPriceRouteImport } from './routes/_app.pricing.quick-price'
import { Route as AppPricingPurchasePricesRouteImport } from './routes/_app.pricing.purchase-prices'
import { Route as AppPricingLivePriceListRouteImport } from './routes/_app.pricing.live-price-list'
import { Route as AppPricingCurrencyRatesRouteImport } from './routes/_app.pricing.currency-rates'
import { Route as AppPricingChangeReasonsRouteImport } from './routes/_app.pricing.change-reasons'
import { Route as AppPricingCalculatorRouteImport } from './routes/_app.pricing.calculator'
import { Route as AppDataTablesNewRouteImport } from './routes/_app.data-tables.new'
import { Route as AppDataTablesTableIdRouteImport } from './routes/_app.data-tables.$tableId'
import { Route as AppBotApiKeysUsageRouteImport } from './routes/_app.bot-api-keys.usage'
import { Route as AppBotApiKeysDocsRouteImport } from './routes/_app.bot-api-keys.docs'
import { Route as AppSalesQuotesIndexRouteImport } from './routes/_app.sales.quotes.index'
import { Route as AppSalesQuotesNewRouteImport } from './routes/_app.sales.quotes.new'
import { Route as AppSalesQuotesQuoteIdRouteImport } from './routes/_app.sales.quotes.$quoteId'
import { Route as AppProductsIdEditRouteImport } from './routes/_app.products.$id.edit'
import { Route as ApiPublicBotDynamicTablesTableIdRowsRouteImport } from './routes/api.public.bot.dynamic-tables.$tableId.rows'
import { Route as ApiPublicBotDynamicTablesTableIdRowsRowIdRouteImport } from './routes/api.public.bot.dynamic-tables.$tableId.rows.$rowId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListsRoute = AppPriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBotApiKeysRoute = AppBotApiKeysRouteImport.update({
  id: '/bot-api-keys',
  path: '/bot-api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingIndexRoute = AppPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTablesIndexRoute = AppDataTablesIndexRouteImport.update({
  id: '/data-tables/',
  path: '/data-tables/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesStockAlertsRoute = AppSalesStockAlertsRouteImport.update({
  id: '/stock-alerts',
  path: '/stock-alerts',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesSendQueueRoute = AppSalesSendQueueRouteImport.update({
  id: '/send-queue',
  path: '/send-queue',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesSearchRoute = AppSalesSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuotesRoute = AppSalesQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuoteShareLogsRoute = AppSalesQuoteShareLogsRouteImport.update({
  id: '/quote-share-logs',
  path: '/quote-share-logs',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsLabelsRoute = AppProductsLabelsRouteImport.update({
  id: '/products/labels',
  path: '/products/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsCategoriesRoute = AppProductsCategoriesRouteImport.update({
  id: '/products/categories',
  path: '/products/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsBrandsRoute = AppProductsBrandsRouteImport.update({
  id: '/products/brands',
  path: '/products/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingShippingRulesRoute = AppPricingShippingRulesRouteImport.update({
  id: '/pricing/shipping-rules',
  path: '/pricing/shipping-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingSalePriceTypesRoute =
  AppPricingSalePriceTypesRouteImport.update({
    id: '/pricing/sale-price-types',
    path: '/pricing/sale-price-types',
    getParentRoute: () => AppRoute,
  } as any)
const AppPricingRulesRoute = AppPricingRulesRouteImport.update({
  id: '/pricing/rules',
  path: '/pricing/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingQuickPriceRoute = AppPricingQuickPriceRouteImport.update({
  id: '/pricing/quick-price',
  path: '/pricing/quick-price',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingPurchasePricesRoute =
  AppPricingPurchasePricesRouteImport.update({
    id: '/pricing/purchase-prices',
    path: '/pricing/purchase-prices',
    getParentRoute: () => AppRoute,
  } as any)
const AppPricingLivePriceListRoute = AppPricingLivePriceListRouteImport.update({
  id: '/pricing/live-price-list',
  path: '/pricing/live-price-list',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingCurrencyRatesRoute = AppPricingCurrencyRatesRouteImport.update({
  id: '/pricing/currency-rates',
  path: '/pricing/currency-rates',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingChangeReasonsRoute = AppPricingChangeReasonsRouteImport.update({
  id: '/pricing/change-reasons',
  path: '/pricing/change-reasons',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingCalculatorRoute = AppPricingCalculatorRouteImport.update({
  id: '/pricing/calculator',
  path: '/pricing/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTablesNewRoute = AppDataTablesNewRouteImport.update({
  id: '/data-tables/new',
  path: '/data-tables/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTablesTableIdRoute = AppDataTablesTableIdRouteImport.update({
  id: '/data-tables/$tableId',
  path: '/data-tables/$tableId',
  getParentRoute: () => AppRoute,
} as any)
const AppBotApiKeysUsageRoute = AppBotApiKeysUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppBotApiKeysRoute,
} as any)
const AppBotApiKeysDocsRoute = AppBotApiKeysDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppBotApiKeysRoute,
} as any)
const AppSalesQuotesIndexRoute = AppSalesQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesQuotesRoute,
} as any)
const AppSalesQuotesNewRoute = AppSalesQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSalesQuotesRoute,
} as any)
const AppSalesQuotesQuoteIdRoute = AppSalesQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => AppSalesQuotesRoute,
} as any)
const AppProductsIdEditRoute = AppProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProductsIdRoute,
} as any)
const ApiPublicBotDynamicTablesTableIdRowsRoute =
  ApiPublicBotDynamicTablesTableIdRowsRouteImport.update({
    id: '/api/public/bot/dynamic-tables/$tableId/rows',
    path: '/api/public/bot/dynamic-tables/$tableId/rows',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotDynamicTablesTableIdRowsRowIdRoute =
  ApiPublicBotDynamicTablesTableIdRowsRowIdRouteImport.update({
    id: '/$rowId',
    path: '/$rowId',
    getParentRoute: () => ApiPublicBotDynamicTablesTableIdRowsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/bot-api-keys': typeof AppBotApiKeysRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/invoices': typeof AppInvoicesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/messages': typeof AppMessagesRoute
  '/price-lists': typeof AppPriceListsRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRouteWithChildren
  '/users': typeof AppUsersRoute
  '/bot-api-keys/docs': typeof AppBotApiKeysDocsRoute
  '/bot-api-keys/usage': typeof AppBotApiKeysUsageRoute
  '/data-tables/$tableId': typeof AppDataTablesTableIdRoute
  '/data-tables/new': typeof AppDataTablesNewRoute
  '/pricing/calculator': typeof AppPricingCalculatorRoute
  '/pricing/change-reasons': typeof AppPricingChangeReasonsRoute
  '/pricing/currency-rates': typeof AppPricingCurrencyRatesRoute
  '/pricing/live-price-list': typeof AppPricingLivePriceListRoute
  '/pricing/purchase-prices': typeof AppPricingPurchasePricesRoute
  '/pricing/quick-price': typeof AppPricingQuickPriceRoute
  '/pricing/rules': typeof AppPricingRulesRoute
  '/pricing/sale-price-types': typeof AppPricingSalePriceTypesRoute
  '/pricing/shipping-rules': typeof AppPricingShippingRulesRoute
  '/products/$id': typeof AppProductsIdRouteWithChildren
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/labels': typeof AppProductsLabelsRoute
  '/products/new': typeof AppProductsNewRoute
  '/sales/quote-share-logs': typeof AppSalesQuoteShareLogsRoute
  '/sales/quotes': typeof AppSalesQuotesRouteWithChildren
  '/sales/search': typeof AppSalesSearchRoute
  '/sales/send-queue': typeof AppSalesSendQueueRoute
  '/sales/stock-alerts': typeof AppSalesStockAlertsRoute
  '/data-tables/': typeof AppDataTablesIndexRoute
  '/pricing/': typeof AppPricingIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/sales/quotes/$quoteId': typeof AppSalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof AppSalesQuotesNewRoute
  '/sales/quotes/': typeof AppSalesQuotesIndexRoute
  '/api/public/bot/dynamic-tables/$tableId/rows': typeof ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren
  '/api/public/bot/dynamic-tables/$tableId/rows/$rowId': typeof ApiPublicBotDynamicTablesTableIdRowsRowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/bot-api-keys': typeof AppBotApiKeysRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/invoices': typeof AppInvoicesRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/messages': typeof AppMessagesRoute
  '/price-lists': typeof AppPriceListsRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/users': typeof AppUsersRoute
  '/bot-api-keys/docs': typeof AppBotApiKeysDocsRoute
  '/bot-api-keys/usage': typeof AppBotApiKeysUsageRoute
  '/data-tables/$tableId': typeof AppDataTablesTableIdRoute
  '/data-tables/new': typeof AppDataTablesNewRoute
  '/pricing/calculator': typeof AppPricingCalculatorRoute
  '/pricing/change-reasons': typeof AppPricingChangeReasonsRoute
  '/pricing/currency-rates': typeof AppPricingCurrencyRatesRoute
  '/pricing/live-price-list': typeof AppPricingLivePriceListRoute
  '/pricing/purchase-prices': typeof AppPricingPurchasePricesRoute
  '/pricing/quick-price': typeof AppPricingQuickPriceRoute
  '/pricing/rules': typeof AppPricingRulesRoute
  '/pricing/sale-price-types': typeof AppPricingSalePriceTypesRoute
  '/pricing/shipping-rules': typeof AppPricingShippingRulesRoute
  '/products/$id': typeof AppProductsIdRouteWithChildren
  '/products/brands': typeof AppProductsBrandsRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/labels': typeof AppProductsLabelsRoute
  '/products/new': typeof AppProductsNewRoute
  '/sales/quote-share-logs': typeof AppSalesQuoteShareLogsRoute
  '/sales/search': typeof AppSalesSearchRoute
  '/sales/send-queue': typeof AppSalesSendQueueRoute
  '/sales/stock-alerts': typeof AppSalesStockAlertsRoute
  '/data-tables': typeof AppDataTablesIndexRoute
  '/pricing': typeof AppPricingIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/sales/quotes/$quoteId': typeof AppSalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof AppSalesQuotesNewRoute
  '/sales/quotes': typeof AppSalesQuotesIndexRoute
  '/api/public/bot/dynamic-tables/$tableId/rows': typeof ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren
  '/api/public/bot/dynamic-tables/$tableId/rows/$rowId': typeof ApiPublicBotDynamicTablesTableIdRowsRowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/bot-api-keys': typeof AppBotApiKeysRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/price-lists': typeof AppPriceListsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/_app/bot-api-keys/docs': typeof AppBotApiKeysDocsRoute
  '/_app/bot-api-keys/usage': typeof AppBotApiKeysUsageRoute
  '/_app/data-tables/$tableId': typeof AppDataTablesTableIdRoute
  '/_app/data-tables/new': typeof AppDataTablesNewRoute
  '/_app/pricing/calculator': typeof AppPricingCalculatorRoute
  '/_app/pricing/change-reasons': typeof AppPricingChangeReasonsRoute
  '/_app/pricing/currency-rates': typeof AppPricingCurrencyRatesRoute
  '/_app/pricing/live-price-list': typeof AppPricingLivePriceListRoute
  '/_app/pricing/purchase-prices': typeof AppPricingPurchasePricesRoute
  '/_app/pricing/quick-price': typeof AppPricingQuickPriceRoute
  '/_app/pricing/rules': typeof AppPricingRulesRoute
  '/_app/pricing/sale-price-types': typeof AppPricingSalePriceTypesRoute
  '/_app/pricing/shipping-rules': typeof AppPricingShippingRulesRoute
  '/_app/products/$id': typeof AppProductsIdRouteWithChildren
  '/_app/products/brands': typeof AppProductsBrandsRoute
  '/_app/products/categories': typeof AppProductsCategoriesRoute
  '/_app/products/labels': typeof AppProductsLabelsRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/sales/quote-share-logs': typeof AppSalesQuoteShareLogsRoute
  '/_app/sales/quotes': typeof AppSalesQuotesRouteWithChildren
  '/_app/sales/search': typeof AppSalesSearchRoute
  '/_app/sales/send-queue': typeof AppSalesSendQueueRoute
  '/_app/sales/stock-alerts': typeof AppSalesStockAlertsRoute
  '/_app/data-tables/': typeof AppDataTablesIndexRoute
  '/_app/pricing/': typeof AppPricingIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/products/$id/edit': typeof AppProductsIdEditRoute
  '/_app/sales/quotes/$quoteId': typeof AppSalesQuotesQuoteIdRoute
  '/_app/sales/quotes/new': typeof AppSalesQuotesNewRoute
  '/_app/sales/quotes/': typeof AppSalesQuotesIndexRoute
  '/api/public/bot/dynamic-tables/$tableId/rows': typeof ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren
  '/api/public/bot/dynamic-tables/$tableId/rows/$rowId': typeof ApiPublicBotDynamicTablesTableIdRowsRowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/audit-logs'
    | '/bot-api-keys'
    | '/dashboard'
    | '/feedback'
    | '/invoices'
    | '/knowledge'
    | '/messages'
    | '/price-lists'
    | '/purchases'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/users'
    | '/bot-api-keys/docs'
    | '/bot-api-keys/usage'
    | '/data-tables/$tableId'
    | '/data-tables/new'
    | '/pricing/calculator'
    | '/pricing/change-reasons'
    | '/pricing/currency-rates'
    | '/pricing/live-price-list'
    | '/pricing/purchase-prices'
    | '/pricing/quick-price'
    | '/pricing/rules'
    | '/pricing/sale-price-types'
    | '/pricing/shipping-rules'
    | '/products/$id'
    | '/products/brands'
    | '/products/categories'
    | '/products/labels'
    | '/products/new'
    | '/sales/quote-share-logs'
    | '/sales/quotes'
    | '/sales/search'
    | '/sales/send-queue'
    | '/sales/stock-alerts'
    | '/data-tables/'
    | '/pricing/'
    | '/products/'
    | '/sales/'
    | '/products/$id/edit'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/sales/quotes/'
    | '/api/public/bot/dynamic-tables/$tableId/rows'
    | '/api/public/bot/dynamic-tables/$tableId/rows/$rowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/audit-logs'
    | '/bot-api-keys'
    | '/dashboard'
    | '/feedback'
    | '/invoices'
    | '/knowledge'
    | '/messages'
    | '/price-lists'
    | '/purchases'
    | '/reports'
    | '/roles'
    | '/users'
    | '/bot-api-keys/docs'
    | '/bot-api-keys/usage'
    | '/data-tables/$tableId'
    | '/data-tables/new'
    | '/pricing/calculator'
    | '/pricing/change-reasons'
    | '/pricing/currency-rates'
    | '/pricing/live-price-list'
    | '/pricing/purchase-prices'
    | '/pricing/quick-price'
    | '/pricing/rules'
    | '/pricing/sale-price-types'
    | '/pricing/shipping-rules'
    | '/products/$id'
    | '/products/brands'
    | '/products/categories'
    | '/products/labels'
    | '/products/new'
    | '/sales/quote-share-logs'
    | '/sales/search'
    | '/sales/send-queue'
    | '/sales/stock-alerts'
    | '/data-tables'
    | '/pricing'
    | '/products'
    | '/sales'
    | '/products/$id/edit'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/sales/quotes'
    | '/api/public/bot/dynamic-tables/$tableId/rows'
    | '/api/public/bot/dynamic-tables/$tableId/rows/$rowId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/_app/audit-logs'
    | '/_app/bot-api-keys'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/invoices'
    | '/_app/knowledge'
    | '/_app/messages'
    | '/_app/price-lists'
    | '/_app/purchases'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/sales'
    | '/_app/users'
    | '/_app/bot-api-keys/docs'
    | '/_app/bot-api-keys/usage'
    | '/_app/data-tables/$tableId'
    | '/_app/data-tables/new'
    | '/_app/pricing/calculator'
    | '/_app/pricing/change-reasons'
    | '/_app/pricing/currency-rates'
    | '/_app/pricing/live-price-list'
    | '/_app/pricing/purchase-prices'
    | '/_app/pricing/quick-price'
    | '/_app/pricing/rules'
    | '/_app/pricing/sale-price-types'
    | '/_app/pricing/shipping-rules'
    | '/_app/products/$id'
    | '/_app/products/brands'
    | '/_app/products/categories'
    | '/_app/products/labels'
    | '/_app/products/new'
    | '/_app/sales/quote-share-logs'
    | '/_app/sales/quotes'
    | '/_app/sales/search'
    | '/_app/sales/send-queue'
    | '/_app/sales/stock-alerts'
    | '/_app/data-tables/'
    | '/_app/pricing/'
    | '/_app/products/'
    | '/_app/sales/'
    | '/_app/products/$id/edit'
    | '/_app/sales/quotes/$quoteId'
    | '/_app/sales/quotes/new'
    | '/_app/sales/quotes/'
    | '/api/public/bot/dynamic-tables/$tableId/rows'
    | '/api/public/bot/dynamic-tables/$tableId/rows/$rowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiPublicBotDynamicTablesTableIdRowsRoute: typeof ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-lists': {
      id: '/_app/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof AppPriceListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bot-api-keys': {
      id: '/_app/bot-api-keys'
      path: '/bot-api-keys'
      fullPath: '/bot-api-keys'
      preLoaderRoute: typeof AppBotApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/': {
      id: '/_app/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AppPricingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-tables/': {
      id: '/_app/data-tables/'
      path: '/data-tables'
      fullPath: '/data-tables/'
      preLoaderRoute: typeof AppDataTablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/stock-alerts': {
      id: '/_app/sales/stock-alerts'
      path: '/stock-alerts'
      fullPath: '/sales/stock-alerts'
      preLoaderRoute: typeof AppSalesStockAlertsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/send-queue': {
      id: '/_app/sales/send-queue'
      path: '/send-queue'
      fullPath: '/sales/send-queue'
      preLoaderRoute: typeof AppSalesSendQueueRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/search': {
      id: '/_app/sales/search'
      path: '/search'
      fullPath: '/sales/search'
      preLoaderRoute: typeof AppSalesSearchRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quotes': {
      id: '/_app/sales/quotes'
      path: '/quotes'
      fullPath: '/sales/quotes'
      preLoaderRoute: typeof AppSalesQuotesRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quote-share-logs': {
      id: '/_app/sales/quote-share-logs'
      path: '/quote-share-logs'
      fullPath: '/sales/quote-share-logs'
      preLoaderRoute: typeof AppSalesQuoteShareLogsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/labels': {
      id: '/_app/products/labels'
      path: '/products/labels'
      fullPath: '/products/labels'
      preLoaderRoute: typeof AppProductsLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/categories': {
      id: '/_app/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AppProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/brands': {
      id: '/_app/products/brands'
      path: '/products/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof AppProductsBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/shipping-rules': {
      id: '/_app/pricing/shipping-rules'
      path: '/pricing/shipping-rules'
      fullPath: '/pricing/shipping-rules'
      preLoaderRoute: typeof AppPricingShippingRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/sale-price-types': {
      id: '/_app/pricing/sale-price-types'
      path: '/pricing/sale-price-types'
      fullPath: '/pricing/sale-price-types'
      preLoaderRoute: typeof AppPricingSalePriceTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/rules': {
      id: '/_app/pricing/rules'
      path: '/pricing/rules'
      fullPath: '/pricing/rules'
      preLoaderRoute: typeof AppPricingRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/quick-price': {
      id: '/_app/pricing/quick-price'
      path: '/pricing/quick-price'
      fullPath: '/pricing/quick-price'
      preLoaderRoute: typeof AppPricingQuickPriceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/purchase-prices': {
      id: '/_app/pricing/purchase-prices'
      path: '/pricing/purchase-prices'
      fullPath: '/pricing/purchase-prices'
      preLoaderRoute: typeof AppPricingPurchasePricesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/live-price-list': {
      id: '/_app/pricing/live-price-list'
      path: '/pricing/live-price-list'
      fullPath: '/pricing/live-price-list'
      preLoaderRoute: typeof AppPricingLivePriceListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/currency-rates': {
      id: '/_app/pricing/currency-rates'
      path: '/pricing/currency-rates'
      fullPath: '/pricing/currency-rates'
      preLoaderRoute: typeof AppPricingCurrencyRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/change-reasons': {
      id: '/_app/pricing/change-reasons'
      path: '/pricing/change-reasons'
      fullPath: '/pricing/change-reasons'
      preLoaderRoute: typeof AppPricingChangeReasonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/calculator': {
      id: '/_app/pricing/calculator'
      path: '/pricing/calculator'
      fullPath: '/pricing/calculator'
      preLoaderRoute: typeof AppPricingCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-tables/new': {
      id: '/_app/data-tables/new'
      path: '/data-tables/new'
      fullPath: '/data-tables/new'
      preLoaderRoute: typeof AppDataTablesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-tables/$tableId': {
      id: '/_app/data-tables/$tableId'
      path: '/data-tables/$tableId'
      fullPath: '/data-tables/$tableId'
      preLoaderRoute: typeof AppDataTablesTableIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bot-api-keys/usage': {
      id: '/_app/bot-api-keys/usage'
      path: '/usage'
      fullPath: '/bot-api-keys/usage'
      preLoaderRoute: typeof AppBotApiKeysUsageRouteImport
      parentRoute: typeof AppBotApiKeysRoute
    }
    '/_app/bot-api-keys/docs': {
      id: '/_app/bot-api-keys/docs'
      path: '/docs'
      fullPath: '/bot-api-keys/docs'
      preLoaderRoute: typeof AppBotApiKeysDocsRouteImport
      parentRoute: typeof AppBotApiKeysRoute
    }
    '/_app/sales/quotes/': {
      id: '/_app/sales/quotes/'
      path: '/'
      fullPath: '/sales/quotes/'
      preLoaderRoute: typeof AppSalesQuotesIndexRouteImport
      parentRoute: typeof AppSalesQuotesRoute
    }
    '/_app/sales/quotes/new': {
      id: '/_app/sales/quotes/new'
      path: '/new'
      fullPath: '/sales/quotes/new'
      preLoaderRoute: typeof AppSalesQuotesNewRouteImport
      parentRoute: typeof AppSalesQuotesRoute
    }
    '/_app/sales/quotes/$quoteId': {
      id: '/_app/sales/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/sales/quotes/$quoteId'
      preLoaderRoute: typeof AppSalesQuotesQuoteIdRouteImport
      parentRoute: typeof AppSalesQuotesRoute
    }
    '/_app/products/$id/edit': {
      id: '/_app/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AppProductsIdEditRouteImport
      parentRoute: typeof AppProductsIdRoute
    }
    '/api/public/bot/dynamic-tables/$tableId/rows': {
      id: '/api/public/bot/dynamic-tables/$tableId/rows'
      path: '/api/public/bot/dynamic-tables/$tableId/rows'
      fullPath: '/api/public/bot/dynamic-tables/$tableId/rows'
      preLoaderRoute: typeof ApiPublicBotDynamicTablesTableIdRowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/dynamic-tables/$tableId/rows/$rowId': {
      id: '/api/public/bot/dynamic-tables/$tableId/rows/$rowId'
      path: '/$rowId'
      fullPath: '/api/public/bot/dynamic-tables/$tableId/rows/$rowId'
      preLoaderRoute: typeof ApiPublicBotDynamicTablesTableIdRowsRowIdRouteImport
      parentRoute: typeof ApiPublicBotDynamicTablesTableIdRowsRoute
    }
  }
}

interface AppBotApiKeysRouteChildren {
  AppBotApiKeysDocsRoute: typeof AppBotApiKeysDocsRoute
  AppBotApiKeysUsageRoute: typeof AppBotApiKeysUsageRoute
}

const AppBotApiKeysRouteChildren: AppBotApiKeysRouteChildren = {
  AppBotApiKeysDocsRoute: AppBotApiKeysDocsRoute,
  AppBotApiKeysUsageRoute: AppBotApiKeysUsageRoute,
}

const AppBotApiKeysRouteWithChildren = AppBotApiKeysRoute._addFileChildren(
  AppBotApiKeysRouteChildren,
)

interface AppSalesQuotesRouteChildren {
  AppSalesQuotesQuoteIdRoute: typeof AppSalesQuotesQuoteIdRoute
  AppSalesQuotesNewRoute: typeof AppSalesQuotesNewRoute
  AppSalesQuotesIndexRoute: typeof AppSalesQuotesIndexRoute
}

const AppSalesQuotesRouteChildren: AppSalesQuotesRouteChildren = {
  AppSalesQuotesQuoteIdRoute: AppSalesQuotesQuoteIdRoute,
  AppSalesQuotesNewRoute: AppSalesQuotesNewRoute,
  AppSalesQuotesIndexRoute: AppSalesQuotesIndexRoute,
}

const AppSalesQuotesRouteWithChildren = AppSalesQuotesRoute._addFileChildren(
  AppSalesQuotesRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesQuoteShareLogsRoute: typeof AppSalesQuoteShareLogsRoute
  AppSalesQuotesRoute: typeof AppSalesQuotesRouteWithChildren
  AppSalesSearchRoute: typeof AppSalesSearchRoute
  AppSalesSendQueueRoute: typeof AppSalesSendQueueRoute
  AppSalesStockAlertsRoute: typeof AppSalesStockAlertsRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesQuoteShareLogsRoute: AppSalesQuoteShareLogsRoute,
  AppSalesQuotesRoute: AppSalesQuotesRouteWithChildren,
  AppSalesSearchRoute: AppSalesSearchRoute,
  AppSalesSendQueueRoute: AppSalesSendQueueRoute,
  AppSalesStockAlertsRoute: AppSalesStockAlertsRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppProductsIdRouteChildren {
  AppProductsIdEditRoute: typeof AppProductsIdEditRoute
}

const AppProductsIdRouteChildren: AppProductsIdRouteChildren = {
  AppProductsIdEditRoute: AppProductsIdEditRoute,
}

const AppProductsIdRouteWithChildren = AppProductsIdRoute._addFileChildren(
  AppProductsIdRouteChildren,
)

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBotApiKeysRoute: typeof AppBotApiKeysRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPriceListsRoute: typeof AppPriceListsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppDataTablesTableIdRoute: typeof AppDataTablesTableIdRoute
  AppDataTablesNewRoute: typeof AppDataTablesNewRoute
  AppPricingCalculatorRoute: typeof AppPricingCalculatorRoute
  AppPricingChangeReasonsRoute: typeof AppPricingChangeReasonsRoute
  AppPricingCurrencyRatesRoute: typeof AppPricingCurrencyRatesRoute
  AppPricingLivePriceListRoute: typeof AppPricingLivePriceListRoute
  AppPricingPurchasePricesRoute: typeof AppPricingPurchasePricesRoute
  AppPricingQuickPriceRoute: typeof AppPricingQuickPriceRoute
  AppPricingRulesRoute: typeof AppPricingRulesRoute
  AppPricingSalePriceTypesRoute: typeof AppPricingSalePriceTypesRoute
  AppPricingShippingRulesRoute: typeof AppPricingShippingRulesRoute
  AppProductsIdRoute: typeof AppProductsIdRouteWithChildren
  AppProductsBrandsRoute: typeof AppProductsBrandsRoute
  AppProductsCategoriesRoute: typeof AppProductsCategoriesRoute
  AppProductsLabelsRoute: typeof AppProductsLabelsRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppDataTablesIndexRoute: typeof AppDataTablesIndexRoute
  AppPricingIndexRoute: typeof AppPricingIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBotApiKeysRoute: AppBotApiKeysRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPriceListsRoute: AppPriceListsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppDataTablesTableIdRoute: AppDataTablesTableIdRoute,
  AppDataTablesNewRoute: AppDataTablesNewRoute,
  AppPricingCalculatorRoute: AppPricingCalculatorRoute,
  AppPricingChangeReasonsRoute: AppPricingChangeReasonsRoute,
  AppPricingCurrencyRatesRoute: AppPricingCurrencyRatesRoute,
  AppPricingLivePriceListRoute: AppPricingLivePriceListRoute,
  AppPricingPurchasePricesRoute: AppPricingPurchasePricesRoute,
  AppPricingQuickPriceRoute: AppPricingQuickPriceRoute,
  AppPricingRulesRoute: AppPricingRulesRoute,
  AppPricingSalePriceTypesRoute: AppPricingSalePriceTypesRoute,
  AppPricingShippingRulesRoute: AppPricingShippingRulesRoute,
  AppProductsIdRoute: AppProductsIdRouteWithChildren,
  AppProductsBrandsRoute: AppProductsBrandsRoute,
  AppProductsCategoriesRoute: AppProductsCategoriesRoute,
  AppProductsLabelsRoute: AppProductsLabelsRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppDataTablesIndexRoute: AppDataTablesIndexRoute,
  AppPricingIndexRoute: AppPricingIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiPublicBotDynamicTablesTableIdRowsRouteChildren {
  ApiPublicBotDynamicTablesTableIdRowsRowIdRoute: typeof ApiPublicBotDynamicTablesTableIdRowsRowIdRoute
}

const ApiPublicBotDynamicTablesTableIdRowsRouteChildren: ApiPublicBotDynamicTablesTableIdRowsRouteChildren =
  {
    ApiPublicBotDynamicTablesTableIdRowsRowIdRoute:
      ApiPublicBotDynamicTablesTableIdRowsRowIdRoute,
  }

const ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren =
  ApiPublicBotDynamicTablesTableIdRowsRoute._addFileChildren(
    ApiPublicBotDynamicTablesTableIdRowsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiPublicBotDynamicTablesTableIdRowsRoute:
    ApiPublicBotDynamicTablesTableIdRowsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
