SET client_encoding='UTF8';

-- ============================================================================================
-- 534 · cron_run_log (E-5 / mission Convergence)
--
-- Written by the two new cron-only wrapper functions from migration 533
-- (run_issabel_import(), generate_birthday_notifications_worker()). Neither function's body
-- changes after this migration; both already reference public.cron_run_log by name. Applying
-- 533 without 534 leaves those two INSERT/UPDATE statements referencing a table that does not
-- exist yet -- harmless until the function is actually invoked (PL/pgSQL does not resolve a
-- statement's tables until that statement first executes), but the two migrations are meant to
-- be applied back to back, in filename order, same as every other pair in this repo.
--
-- Columns follow the brief literally: job name, started_at, finished_at, status, http status
-- if applicable, error text. `id` is a surrogate key so a function can UPDATE the row it just
-- INSERTed (RETURNING id) rather than matching on job_name + started_at.
--
-- RLS: admin/manager READ only, no other policy. Both writers are SECURITY DEFINER functions
-- owned by supabase_admin (superuser on this cluster -- confirmed live: RLS does not apply to a
-- superuser regardless of policies), so no INSERT/UPDATE policy is needed for the write path
-- this migration actually uses. If a future non-superuser writer is added, it needs its own
-- policy at that time -- not added speculatively here.
-- ============================================================================================

CREATE TABLE IF NOT EXISTS public.cron_run_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name     text NOT NULL,
  started_at   timestamptz NOT NULL DEFAULT now(),
  finished_at  timestamptz,
  status       text NOT NULL DEFAULT 'running'
                 CHECK (status IN ('running', 'succeeded', 'failed')),
  http_status  integer,
  error_text   text
);

COMMENT ON TABLE public.cron_run_log IS
  'Migration 534. One row per invocation of a pg_cron-driven wrapper function '
  '(run_issabel_import, generate_birthday_notifications_worker -- migration 533). '
  'http_status is populated only by jobs that make an HTTP call; NULL otherwise. '
  'Admin/manager read-only via RLS; written exclusively by SECURITY DEFINER functions.';

CREATE INDEX IF NOT EXISTS idx_cron_run_log_job_started
  ON public.cron_run_log (job_name, started_at DESC);

ALTER TABLE public.cron_run_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cron_run_log_admin_manager_read ON public.cron_run_log;
CREATE POLICY cron_run_log_admin_manager_read ON public.cron_run_log
  FOR SELECT TO authenticated
  USING (public.has_any_role(auth.uid(), ARRAY['admin', 'manager']::text[]));

-- No INSERT/UPDATE/DELETE policy is created: RLS defaults to deny for any command with no
-- matching policy, and the only writers (533's two SECURITY DEFINER functions, owned by
-- supabase_admin) bypass RLS as the superuser regardless. A browser session -- even an
-- admin's -- therefore cannot write to this table, only read it.

DO $$
BEGIN
  IF has_table_privilege('anon', 'public.cron_run_log', 'SELECT') THEN
    RAISE EXCEPTION '534: anon can read cron_run_log';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public' AND tablename = 'cron_run_log'
       AND policyname = 'cron_run_log_admin_manager_read'
  ) THEN
    RAISE EXCEPTION '534: the admin/manager read policy did not get created';
  END IF;
END $$;
