import {
  LayoutDashboard,
  Package,
  DollarSign,
  ShoppingCart,
  ShoppingBag,
  FileText,
  ListOrdered,
  Users,
  ShieldCheck,
  BarChart3,
  BookOpen,
  MessageSquare,
  ScrollText,
  Database,
  KeyRound,
  UserSquare2,
  Factory,
  GraduationCap,
  CheckSquare,
  Workflow,
  Settings,
  Heart,
  Megaphone,
  Edit3,
  Monitor,
  TrendingUp,
  Trophy,
  Wallet,
  Coins,
  Plus,
  Tag,
  Layers,
  Bookmark,
  Bell,
  Calculator,
  Sparkles,
  Banknote,
  AlertTriangle,
  Send,
  Share2,
  Receipt,
  CreditCard,
  BadgeCheck,
  LifeBuoy,
  FileCheck,
  ClipboardList,
  Plug,
} from "lucide-react";
import type { ModuleKey } from "@/lib/rbac/roles";
import type { AppRole } from "@/lib/rbac/roles";
import type { NavigationEntry, NavigationEntrySeed, NavigationPrimaryModule } from "./types";

const NAVIGATION_SEEDS = [
  // ۱) داشبورد
  { to: "/dashboard", label: "داشبورد", icon: LayoutDashboard, module: "dashboard", group: "main" },
  { to: "/notifications", label: "اعلان‌ها", icon: Bell, module: "messages", group: "main" },
  { to: "/popup-center", label: "مرکز پاپ‌آپ‌ها", icon: Bell, module: "dashboard", group: "main" },
  {
    to: "/collaboration",
    label: "ارتباطات همکاری",
    icon: MessageSquare,
    module: "messages",
    group: "main",
  },

  // ۲) محصولات و قیمت‌گذاری
  {
    to: "/products",
    label: "محصولات",
    icon: Package,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/new",
    label: "افزودن محصول",
    icon: Plus,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/categories",
    label: "دسته‌بندی‌ها",
    icon: Layers,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/brands",
    label: "برندها",
    icon: Bookmark,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/attributes",
    label: "ویژگی‌ها",
    icon: Tag,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/products/labels",
    label: "برچسب‌ها",
    icon: Tag,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-catalog",
  },
  {
    to: "/pricing/purchase-prices",
    label: "قیمت‌های خرید",
    icon: ShoppingBag,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/rules",
    label: "قوانین قیمت‌گذاری",
    icon: Workflow,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/sale-price-types",
    label: "نوع‌های قیمت فروش",
    icon: DollarSign,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/quick-price",
    label: "قیمت سریع",
    icon: Sparkles,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/calculator",
    label: "ماشین‌حساب قیمت",
    icon: Calculator,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/my-workbench",
    label: "کارگاه قیمت من",
    icon: Edit3,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/attention",
    label: "فرصت جبران",
    icon: LifeBuoy,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/price-alerts",
    label: "هشدارهای قیمت",
    icon: AlertTriangle,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/market-intelligence",
    label: "هوشمند بازار",
    icon: TrendingUp,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-pricing",
  },
  {
    to: "/pricing/product-recommendations",
    label: "پیشنهاد محصولات",
    icon: Sparkles,
    module: "products",
    group: "products-pricing",
    subgroup: "pp-pricing",
    adminOnly: true,
  },
  {
    to: "/pricing/amin-hozoor-board",
    label: "تابلو قیمت زنده",
    icon: Monitor,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/live-price-list",
    label: "لیست قیمت زنده",
    icon: ListOrdered,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/sale-lists",
    label: "لیست قیمت فروش",
    icon: FileText,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  // Phase 9.3 — same situation as /messages: the route exists with
  // requirePermission("price-lists", "view") and is already declared in
  // PRIMARY_MODULES.paths for the catalog module, but had no seed. Guard
  // unchanged.
  {
    to: "/price-lists",
    label: "لیست‌های قیمت",
    icon: ListOrdered,
    module: "price-lists",
    group: "products-pricing",
    subgroup: "pp-publish",
  },
  {
    to: "/pricing/recompute-prices",
    label: "انتشار دسته‌ای قیمت",
    icon: Sparkles,
    module: "pricing",
    group: "products-pricing",
    subgroup: "pp-publish",
    adminOnly: true,
  },

  // ۳) خرید و تأمین‌کنندگان
  {
    to: "/suppliers",
    label: "تأمین‌کنندگان",
    icon: Factory,
    module: "suppliers",
    group: "purchasing",
  },
  {
    to: "/purchases",
    label: "پنل خرید",
    icon: ShoppingBag,
    module: "purchases",
    group: "purchasing",
  },

  // ۴) فروش و مشتریان
  {
    to: "/sales",
    label: "جستجوی سریع فروش",
    icon: ShoppingCart,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/quotes",
    label: "پیش‌فاکتورها",
    icon: FileText,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  // `invoices` / `invoice_items` are a dead parallel design: both tables hold 0
  // rows and the live pre-invoice workflow is `sales_quotes` (/sales/quotes).
  // Hidden from the menus only — routes, guards and breadcrumbs are unchanged,
  // so /sales/invoices/$invoiceId/waybill stays reachable by direct URL.
  {
    to: "/sales/invoices",
    label: "فاکتورهای فروش",
    icon: Receipt,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
    hiddenFromMenu: true,
  },
  {
    to: "/invoices",
    label: "فاکتورها",
    icon: FileText,
    module: "invoices",
    group: "sales-customers",
    subgroup: "sc-sales",
    hiddenFromMenu: true,
  },
  {
    to: "/sales/stock-alerts",
    label: "هشدار موجودی",
    icon: AlertTriangle,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-sales",
  },
  {
    to: "/sales/customers",
    label: "مشتریان",
    icon: UserSquare2,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/persons",
    label: "اشخاص",
    icon: UserSquare2,
    module: "persons",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/sales/credit-customers",
    label: "اعتبار مشتریان",
    icon: BadgeCheck,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  {
    to: "/sales/credit-rules",
    label: "قوانین اعتبار",
    icon: ShieldCheck,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },
  // The route already existed with a `sales/view` guard but was only reachable
  // from a button on /sales/customers.
  {
    to: "/sales/customers/credit-training",
    label: "آموزش اعتبار مشتریان",
    icon: GraduationCap,
    module: "sales",
    group: "sales-customers",
    subgroup: "sc-customers",
  },

  // ۵) مالی و حسابداری
  // UI-NAV.4 — همگی به ماژول جدید «accounting» منتقل شدند تا برای فروشنده/بیننده پنهان شوند.
  {
    to: "/accounting/receipts",
    label: "فیش‌های واریزی",
    icon: Receipt,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/receipts/training",
    label: "آموزش فیش‌های واریزی",
    icon: GraduationCap,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/receivables",
    label: "مطالبات مشتریان",
    icon: Wallet,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/payables",
    label: "بدهی تأمین‌کنندگان",
    icon: Wallet,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/purchase-payments",
    label: "پرداخت خرید",
    icon: CreditCard,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/bank-accounts",
    label: "حساب‌های بانکی",
    icon: Banknote,
    module: "accounting",
    group: "finance",
  },
  {
    to: "/accounting/external-parties",
    label: "طرف‌های حساب",
    icon: UserSquare2,
    module: "accounting",
    group: "finance",
  },
  // Item 141 — the three legacy capital pages
  // (/accounting/customer-capital-allocations, /accounting/salesperson-capital-allocations,
  // /accounting/daily-capital) were removed from navigation. Their routes now
  // redirect to /accounting/dynamic-capital, which is the single official page.
  {
    to: "/accounting/dynamic-capital",
    label: "تخصیص سرمایه پویا",
    icon: Coins,
    module: "accounting",
    group: "finance",
  },

  // ۶) عملیات داخلی
  {
    to: "/operations/tasks",
    label: "برد وظایف",
    icon: CheckSquare,
    module: "invoices",
    group: "operations",
  },
  {
    to: "/operations/daily-mood",
    label: "حال‌وهوای امروز",
    icon: Heart,
    module: "feedback",
    group: "operations",
  },
  {
    to: "/operations/daily-mood/admin",
    label: "مدیریت حال‌وهوا",
    icon: Heart,
    module: "hr",
    group: "operations",
    adminOnly: true,
  },
  {
    to: "/feedback",
    label: "بازخورد",
    icon: MessageSquare,
    module: "feedback",
    group: "operations",
  },
  {
    to: "/gamification",
    label: "داشبورد گیمیفیکیشن",
    icon: Trophy,
    module: "dashboard",
    group: "operations",
  },
  {
    to: "/gamification/leaderboard",
    label: "لیدربورد",
    icon: BarChart3,
    module: "dashboard",
    group: "operations",
  },

  // ۷) گزارش‌ها
  { to: "/reports", label: "گزارش‌ها", icon: BarChart3, module: "reports", group: "reports" },
  {
    to: "/audit-logs",
    label: "لاگ فعالیت‌ها",
    icon: ScrollText,
    module: "audit-logs",
    group: "reports",
    adminOnly: true,
  },
  {
    to: "/sales/quote-share-logs",
    label: "لاگ اشتراک‌گذاری پیش‌فاکتور",
    icon: Share2,
    module: "invoices",
    group: "reports",
  },
  { to: "/sales/send-queue", label: "صف ارسال", icon: Send, module: "invoices", group: "reports" },
  {
    to: "/marketing/suggestions",
    label: "پیشنهادهای تبلیغاتی",
    icon: Megaphone,
    module: "reports",
    group: "reports",
  },
  {
    to: "/marketing/suggestions-history",
    label: "تاریخچه پیشنهادها",
    icon: ScrollText,
    module: "reports",
    group: "reports",
  },

  // ۸) دانش، آکادمی و ارتباطات
  {
    to: "/knowledge",
    label: "دانش سازمانی",
    icon: BookOpen,
    module: "knowledge",
    group: "knowledge-comms",
  },
  {
    to: "/academy",
    label: "آکادمی",
    icon: GraduationCap,
    module: "academy",
    group: "knowledge-comms",
  },
  // Phase 9.3 — /messages already existed with requirePermission("messages",
  // "view") and was already listed in PRIMARY_MODULES.paths for the assistant
  // module, but had no navigation seed, so itemsForModule looked it up and
  // found nothing. The whole messenger was unreachable from the menu. Guard
  // unchanged; this only adds the missing entry.
  {
    to: "/messages",
    label: "پیام‌رسان",
    icon: MessageSquare,
    module: "messages",
    group: "knowledge-comms",
  },
  {
    to: "/data-tables",
    label: "جداول داده پویا",
    icon: Database,
    module: "data-tables",
    group: "knowledge-comms",
  },

  // ۹) مدیریت سیستم
  {
    to: "/users",
    label: "کاربران",
    icon: Users,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
  },
  {
    to: "/users/pending",
    label: "کاربران در انتظار تأیید",
    icon: Users,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/roles",
    label: "نقش‌ها و دسترسی‌ها",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-users",
  },
  {
    to: "/admin/roles",
    label: "مجوزهای پویا",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/admin/profile-fields",
    label: "فیلدهای کاربر",
    icon: UserSquare2,
    module: "users",
    group: "admin",
    subgroup: "adm-users",
    adminOnly: true,
  },
  {
    to: "/admin/settings",
    label: "تنظیمات عمومی",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/penalties",
    label: "کارت‌های قرمز",
    icon: AlertTriangle,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/audit",
    label: "لاگ فعالیت‌ها",
    icon: ClipboardList,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/purchase",
    label: "مدیریت خرید",
    icon: ShoppingCart,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/documents",
    label: "مدیریت اسناد",
    icon: FileText,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/delivery-receipts",
    label: "مدیریت رسیدها",
    icon: FileCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/admin/workflow-settings",
    label: "تنظیمات گردش‌کار",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/marketing-channels",
    label: "کانال‌های تبلیغاتی",
    icon: Megaphone,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/sales-reminders",
    label: "یادآوری‌های فروش",
    icon: MessageSquare,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/payment-terms",
    label: "زمان‌های تسویه",
    icon: Wallet,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/waybill-fields",
    label: "فیلدهای بیجک",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/receipt-fields",
    label: "فیلدهای فیش واریزی",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/recent-purchase-settings",
    label: "وضعیت موجودی پس از خرید",
    icon: Settings,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/workflow-stages",
    label: "مراحل گردش‌کار",
    icon: Workflow,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/validation-rules",
    label: "قوانین اعتبارسنجی",
    icon: ShieldCheck,
    module: "roles",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currencies",
    label: "ارزها",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currency-sources",
    label: "منابع ارز",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/currency-rates",
    label: "نرخ ارز",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/market-rates-workshop",
    label: "کارگاه نرخ ارز و طلا",
    icon: Coins,
    module: "market-rates",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/settlement-types",
    label: "انواع تسویه",
    icon: Wallet,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/shipping-rules",
    label: "قوانین ارسال",
    icon: Workflow,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing/change-reasons",
    label: "دلایل تغییر قیمت",
    icon: ScrollText,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/pricing",
    label: "تنظیمات قیمت‌گذاری",
    icon: DollarSign,
    module: "pricing",
    group: "admin",
    subgroup: "adm-settings",
    adminOnly: true,
  },
  {
    to: "/admin/automation",
    label: "اتوماسیون فاز صفر",
    icon: Sparkles,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/bot-api-keys",
    label: "کلیدهای API ربات",
    icon: KeyRound,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
  },
  {
    to: "/admin/ai-providers",
    label: "ارائه‌دهندگان هوش مصنوعی",
    icon: Sparkles,
    module: "roles",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/integrations/didar",
    label: "یکپارچه‌سازی دیدار",
    icon: Plug,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/market-matches",
    label: "بررسی تطبیق محصولات بازار",
    icon: BadgeCheck,
    module: "bot-api-keys",
    group: "admin",
    subgroup: "adm-tools",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/kpi-rules",
    label: "قوانین امتیازدهی",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/achievements",
    label: "مدیریت مدال‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/missions",
    label: "مدیریت مأموریت‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/leagues",
    label: "مدیریت لیگ‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/rewards",
    label: "مدیریت پاداش‌ها",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/analytics",
    label: "تحلیل گیمیفیکیشن",
    icon: BarChart3,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  {
    to: "/gamification/admin/purchase-settings",
    label: "طلای زمان (خرید)",
    icon: Coins,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
  // Item 132.1 — manual daily performance entry (admin/manager/accountant).
  {
    to: "/gamification/admin/manual-metrics",
    label: "ثبت دستی عملکرد روزانه",
    icon: Trophy,
    module: "roles",
    group: "admin",
    subgroup: "adm-gamification",
    adminOnly: true,
  },
] satisfies NavigationEntrySeed[];

const PRIMARY_MODULE_PATHS: Record<NavigationPrimaryModule, string[]> = {
  dashboard: ["/dashboard", "/notifications", "/operations/tasks", "/operations/daily-mood"],
  assistant: [
    "/pricing/market-intelligence",
    "/pricing/product-recommendations",
    "/pricing/price-alerts",
    "/marketing/suggestions",
    "/marketing/suggestions-history",
    "/messages",
    "/knowledge",
    "/academy",
  ],
  catalog: [
    "/products",
    "/products/new",
    "/products/categories",
    "/products/brands",
    "/products/attributes",
    "/products/labels",
    "/pricing/purchase-prices",
    "/pricing/quick-price",
    "/pricing/calculator",
    "/pricing/my-workbench",
    "/pricing/sale-lists",
    "/price-lists",
    "/pricing/amin-hozoor-board",
    "/pricing/rules",
    "/pricing/sale-price-types",
    "/pricing/recompute-prices",
    "/suppliers",
    "/purchases",
  ],
  sales: [
    "/sales",
    "/sales/customers",
    "/persons",
    "/sales/quotes",
    "/sales/invoices",
    "/invoices",
    "/sales/stock-alerts",
    "/sales/credit-customers",
    "/sales/credit-rules",
    "/sales/customers/credit-training",
    "/sales/send-queue",
  ],
  finance: [
    "/accounting/receipts",
    "/accounting/receipts/training",
    "/accounting/receivables",
    "/accounting/payables",
    "/accounting/purchase-payments",
    "/accounting/bank-accounts",
    "/accounting/external-parties",
    "/accounting/dynamic-capital",
  ],
  analytics: [
    "/reports",
    "/sales/quote-share-logs",
    "/gamification",
    "/gamification/leaderboard",
    "/gamification/admin/analytics",
    "/audit-logs",
    "/data-tables",
  ],
  admin: [
    "/users",
    "/users/pending",
    "/roles",
    "/admin/roles",
    "/admin/profile-fields",
    "/admin/settings",
    "/admin/marketing-channels",
    "/admin/payment-terms",
    "/admin/waybill-fields",
    "/admin/receipt-fields",
    "/admin/recent-purchase-settings",
    "/admin/workflow-stages",
    "/admin/validation-rules",
    "/admin/ai-providers",
    "/pricing/currencies",
    "/pricing/currency-sources",
    "/pricing/currency-rates",
    "/pricing/market-rates-workshop",
    "/pricing/settlement-types",
    "/pricing/shipping-rules",
    "/pricing/change-reasons",
    "/pricing",
    "/bot-api-keys",
    "/market-matches",
    "/operations/daily-mood/admin",
    "/feedback",
  ],
};

const MOBILE_PRIORITIES: Record<string, number> = {
  "/dashboard": 1,
  "/products": 2,
  "/pricing/quick-price": 3,
  "/reports": 4,
  "/sales": 2,
  "/sales/quotes": 3,
  "/pricing/sale-lists": 4,
  "/accounting/receipts": 2,
  "/accounting/receivables": 3,
  "/accounting/dynamic-capital": 4,
  "/notifications": 2,
  "/messages": 3,
};

const PRIMARY_ROLE_ROUTES: Partial<Record<string, AppRole[]>> = {
  "/dashboard": ["admin", "manager", "viewer"],
  "/sales": ["sales"],
  "/accounting/receipts": ["accountant"],
};

const KEYWORDS_BY_ROUTE: Record<string, string[]> = {
  "/sales": ["sales quick search", "jostoju sari forush", "search", "forush", "jostoju"],
  "/sales/search": ["sales quick search", "jostoju sari forush", "search", "forush", "jostoju"],
  "/accounting/receipts": ["receipt", "payment", "fish", "resid", "pardakht"],
  "/accounting/receivables": ["receivable", "debt", "motalebat", "bedehi"],
  "/accounting/dynamic-capital": ["capital", "credit", "sarmaye", "etebar"],
  "/sales/credit-customers": ["credit", "etebar", "customer"],
  "/sales/credit-rules": ["credit", "rules", "etebar", "ghanun"],
  "/pricing/sale-lists": ["price list", "excel", "gheymat", "list"],
  "/pricing/quick-price": ["quick price", "gheymat", "sari"],
  "/pricing/recompute-prices": ["queue", "publish", "price", "saf", "enteshar", "gheymat"],
  "/products": ["product", "catalog", "kala", "mahsool"],
  "/users": ["users", "accounts", "karbar", "access"],
  "/users/pending": ["approval", "pending", "taeed", "entezar"],
  "/knowledge": ["knowledge", "docs", "danesh", "document"],
};

const BADGE_SOURCE_BY_ROUTE: Record<string, NavigationEntry["badgeSource"]> = {
  "/users": { id: "pending-users" },
  "/pricing/recompute-prices": { id: "pricing-recompute-queue" },
};

const ACTION_BY_ROUTE: Partial<Record<string, NavigationEntry["permission"]["action"]>> = {
  "/products/new": "create",
  "/pricing/purchase-prices": "create",
  "/pricing/recompute-prices": "update",
};

const ROLE_ALLOWLIST_BY_ROUTE: Record<string, AppRole[]> = {
  "/accounting/dynamic-capital": ["admin", "accountant"],
  "/admin/audit": ["admin", "manager"],
  "/admin/automation": ["admin", "manager"],
  "/admin/delivery-receipts": ["admin", "manager"],
  "/admin/documents": ["admin", "manager"],
  "/admin/penalties": ["admin", "manager"],
  "/admin/profile-fields": ["admin"],
  "/admin/purchase": ["admin", "manager"],
  "/admin/recent-purchase-settings": ["admin"],
  "/admin/roles": ["admin"],
  "/admin/sales-reminders": ["admin", "manager"],
  "/admin/settings": ["admin"],
  "/admin/ai-providers": ["admin"],
  "/admin/validation-rules": ["admin"],
  "/admin/workflow-settings": ["admin", "manager"],
  "/audit-logs": ["admin"],
  "/gamification/admin/achievements": ["admin", "manager"],
  "/gamification/admin/analytics": ["admin", "manager"],
  "/gamification/admin/kpi-rules": ["admin", "manager"],
  "/gamification/admin/leagues": ["admin", "manager"],
  "/gamification/admin/manual-metrics": ["admin", "manager", "accountant"],
  "/gamification/admin/missions": ["admin", "manager"],
  "/gamification/admin/purchase-settings": ["admin", "manager", "accountant"],
  "/gamification/admin/rewards": ["admin", "manager"],
  "/pricing/market-intelligence": ["admin", "manager", "accountant"],
  "/pricing/product-recommendations": ["admin", "manager"],
  "/roles": ["admin"],
  "/sales/credit-rules": ["admin", "accountant"],
  "/users": ["admin"],
};

function idFromRoute(route: string): string {
  return (
    route
      .replace(/^\/+/, "")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "dashboard"
  );
}

function primaryModuleForRoute(route: string): NavigationPrimaryModule {
  let best: { module: NavigationPrimaryModule; length: number } | null = null;
  for (const [module, paths] of Object.entries(PRIMARY_MODULE_PATHS) as [
    NavigationPrimaryModule,
    string[],
  ][]) {
    for (const path of paths) {
      if (route === path || route.startsWith(path + "/")) {
        if (!best || path.length > best.length) best = { module, length: path.length };
      }
    }
  }
  return best?.module ?? "dashboard";
}

function routeKeywords(seed: NavigationEntrySeed): string[] {
  const routeParts = seed.to.split(/[/-]+/).filter(Boolean);
  return Array.from(new Set([seed.label, ...routeParts, ...(KEYWORDS_BY_ROUTE[seed.to] ?? [])]));
}

function toNavigationEntry(seed: NavigationEntrySeed): NavigationEntry {
  const id = idFromRoute(seed.to);
  return {
    id,
    title: seed.label,
    route: seed.to,
    module: seed.module,
    primaryModule: primaryModuleForRoute(seed.to),
    group: seed.group,
    subgroup: seed.subgroup,
    description: "Open " + seed.label,
    keywords: routeKeywords(seed),
    icon: seed.icon,
    permission: { module: seed.module, action: ACTION_BY_ROUTE[seed.to] ?? "view" },
    adminOnly: seed.adminOnly,
    allowedRoles: seed.allowedRoles ?? ROLE_ALLOWLIST_BY_ROUTE[seed.to],
    hiddenFromMenu: seed.hiddenFromMenu,
    pinnable: !seed.hiddenFromMenu,
    primaryForRoles: PRIMARY_ROLE_ROUTES[seed.to] ?? [],
    badgeSource: BADGE_SOURCE_BY_ROUTE[seed.to],
    breadcrumb: { title: seed.label },
    mobileVisible: MOBILE_PRIORITIES[seed.to] !== undefined,
    mobilePriority: MOBILE_PRIORITIES[seed.to],
    recentEligible: !seed.to.includes("/pending") && !seed.to.includes("/admin/audit"),
    analyticsKey: "nav." + id,
  };
}

export const NAVIGATION_REGISTRY = NAVIGATION_SEEDS.map(toNavigationEntry);

const ids = new Set<string>();
const routes = new Set<string>();
for (const entry of NAVIGATION_REGISTRY) {
  if (ids.has(entry.id)) throw new Error("Duplicate navigation id: " + entry.id);
  if (routes.has(entry.route)) throw new Error("Duplicate navigation route: " + entry.route);
  ids.add(entry.id);
  routes.add(entry.route);
}
